export { default as Detail } from '@/pages/Detail'
export { default as Like } from '@/pages/Like'
export { default as Login } from '@/pages/Login'
export { default as Main } from '@/pages/Main'
export { default as SearchResult } from '@/pages/SearchResult'
export { default as Signup } from '@/pages/Signup'
export { default as User } from '@/pages/User'
